### ISSUE TITLE
Implement validateEndpoint() in WavefrontClient builder

### ISSUE THREAD

**Issue by sushantdewan123** [wavefrontHQ/wavefront-sdk-java#169]
Check if the endpoint is valid i.e. reachable by issuing HTTP request.
Bailout in the builder during instantiation if the endpoint is not valid.

**Comment by attack** [comment]
Fixed in PR #172

**Comment by dkalidindi** [comment]
Off late we are observing issues where there is an ad-hoc Service look-up problem (from Kubernetes service) after object instantiation while posting to k8n proxy. So not rejecting points (in case of exception during sendMetrics) method will still lead to data loss since having check during Object instantiation cannot completely guarantee a network connection all the time.
